// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFEpFakN2xXrD-RivWh02oHzbWZcsHyP0',
    appId: '1:59936558186:web:c2371dfdb11a15bf018e13',
    messagingSenderId: '59936558186',
    projectId: 'hacknation26',
    authDomain: 'hacknation26.firebaseapp.com',
    storageBucket: 'hacknation26.firebasestorage.app',
    measurementId: 'G-SHY46GN2FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoSfO_DuKvrMQFU6J_qzp9FMWp7SRIT6k',
    appId: '1:59936558186:android:c6d8c0bf198cd763018e13',
    messagingSenderId: '59936558186',
    projectId: 'hacknation26',
    storageBucket: 'hacknation26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpQ6RF6LuNCpgIlJn6CYQ5Lx-xbP5ty0M',
    appId: '1:59936558186:ios:4fa9538e7c64c9bc018e13',
    messagingSenderId: '59936558186',
    projectId: 'hacknation26',
    storageBucket: 'hacknation26.firebasestorage.app',
    iosBundleId: 'com.example.hacknation26',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpQ6RF6LuNCpgIlJn6CYQ5Lx-xbP5ty0M',
    appId: '1:59936558186:ios:4fa9538e7c64c9bc018e13',
    messagingSenderId: '59936558186',
    projectId: 'hacknation26',
    storageBucket: 'hacknation26.firebasestorage.app',
    iosBundleId: 'com.example.hacknation26',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFEpFakN2xXrD-RivWh02oHzbWZcsHyP0',
    appId: '1:59936558186:web:2f1164269c0bd634018e13',
    messagingSenderId: '59936558186',
    projectId: 'hacknation26',
    authDomain: 'hacknation26.firebaseapp.com',
    storageBucket: 'hacknation26.firebasestorage.app',
    measurementId: 'G-KXTEG49W0W',
  );

}